# Generated by Django 4.0.4 on 2022-05-10 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(max_length=32, verbose_name='Объект')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization', to='staff_list.organization', verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('job_title', models.CharField(blank=True, max_length=32, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substation', to='staff_list.substation', verbose_name='Объект')),
            ],
        ),
    ]
